name: VRF Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - 'contracts/mocks/VRFTestHelper.sol'
      - 'test/vrf-mock-test.js'
      - 'hardhat.vrf-test.config.js'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'contracts/mocks/VRFTestHelper.sol'
      - 'test/vrf-mock-test.js'
      - 'hardhat.vrf-test.config.js'
  workflow_dispatch:  # Allow manual triggering

jobs:
  hardhat-tests:
    name: VRF Mock Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run VRF Mock Tests
        run: npx hardhat test test/vrf-mock-test.js --config hardhat.vrf-test.config.js 