[profile.default]
src = "contracts/test"
test = "test/forge"
out = "out/forge"
libs = ["node_modules", "lib"]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "forge-std/=lib/forge-std/src/"
]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200 