[profile.default]
src = "contracts"
test = "test"
out = "out"
libs = ["node_modules", "lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
verbosity = 3

[rpc_endpoints]
localhost = "http://localhost:8545" 
